//
// common.env.js
//
const envCommon = {
  CDK_APP_NAME: '',
  CDK_ARTIFACT_S3_REGION: '',
  CDK_DB_DATABASE_NAME: '',
  CDK_DB_PASSWORD: '',
  CDK_DB_PORT: '',
  CDK_DB_USER: '',
  CDK_GITHUB_CONNECTION_ARN: '',
  CDK_GITHUB_OWNER: '',
  CDK_GITHUB_REPO: '',
  CDK_GITHUB_REPO_BRANCH: '',
  CDK_HOSTED_ZONE_ID: '',
  CDK_HOSTNAME: '',
  CDK_HTTPS_CERTIFICATE_ARN: '',
  CDK_SSM_DB_PASSWORD_PATH: '',
  CDK_SSM_DB_PASSWORD_VERSION: '',
  CDK_USE_DATABASE: '',
  CDK_USE_HTTPS_FROM_S3: '',
  KEY_PAIR_NAME: '',
}

module.exports = envCommon
