#
# run-PR-tests.yml
#

name: Run tests on PR

on:
  pull_request:
    branches:
      - main
  
jobs:
  
  run-PR-tests:

    name: Run PR tests
    runs-on: ubuntu-latest
    env:
      GHA_REPO_NAME: 'portfolio-site'
      OVERRIDE_DB_PORT: '5432'
      OVERRIDE_PORT: '80'
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up node 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: Install pnpm and pm2
      run: |
        npm install -g pnpm
        pnpm add --global pm2
    
    - name: Unlock ports <1024 for node
      run: |
        sudo setcap cap_net_bind_service=+ep $(command -v node)

    - name: Install packages
      run: |
        pnpm install --frozen-lockfile
        
    - name: Populate production secrets with test values
      run: |
        pnpm secrets:PR
    
    - name: Setup dev database
      run: |
        pnpm db:PR:setup
    
    - name: Build code
      run: |
        pnpm build:all:PR
        
    - name: Start server (dev/PR)
      id: server
      run: |
        pnpm start:PR
    
    - name: Run all jest tests
      run: |
        pnpm jest:all:PR
